export const categoryColors: {[key: string]: string} = {
  Groceries: "#FFD700",
  Rent: "#FF6347",
  Salary: "#32CD32",
  Freelancing: "#6495ED",
  Utilities: "#00CED1",
  Electronics: "#8A2BE2",
  "Dining Out": "#FFA07A",
  "Breakfast Supplies": "#FFDEAD",
  "Household Items": "#F0E68C",
  "Christmas Gifts": "#FF69B4",
  "New Year Party Supplies": "#DB7093",
  "Thanksgiving Groceries": "#CD863F",
  Bonus: "#6B8E23",
  "Consulting Work": "#4682B4",
  "Part-Time Job": "#DAA520",
  "Online Sales": "#20B2AA",
  "Freelance Writing": "#778899",
  "End of Year Bonus": "#5F9EA0",
  Default: "#D3D3D3",
};

export const categoryEmojies: {[key: string]: string} = {
  Groceries: "🛒",
  Rent: "🏠",
  Salary: "💰",
  Freelancing: "👨‍💻",
  Utilities: "💡",
  Electronics: "💻",
  "Dining Out": "🍽",
  "Breakfast Supplies": "🥐",
  "Household Items": "🏡",
  "Christmas Gifts": "🎁",
  "New Year Party Supplies": "🎉",
  "Thanksgiving Groceries": "🦃",
  Bonus: "🤑",
  "Consulting Work": "💼",
  "Part-Time Job": "⌚",
  "Online Sales": "🛒",
  "Freelance Writing": "✍",
  "End of Year Bonus": "💸",
  Default: "🤞",
};

export const localeRu: {[key: string]: string} = {
  Groceries: "Продукты питания",
  Rent: "Аренда",
  Salary: "Зарплата",
  Freelancing: "Фриланс",
  Utilities: "Утилиты",
  Electronics: "Электроника",
  "Dining Out": "Ужинать вне дома",
  "Breakfast Supplies": "Принадлежности для завтрака",
  "Household Items": "Домашняя утварь",
  "Christmas Gifts": "Подарки на Рождество",
  "New Year Party Supplies": "Новогодние праздничные атрибуты",
  "Thanksgiving Groceries": "Продукты на День Благодарения",
  Bonus: "Бонус",
  "Consulting Work": "Консультационная работа",
  "Part-Time Job": "Неполная работа",
  "Online Sales": "Интернет-продажи",
  "Freelance Writing": "Писатель-фрилансер",
  "End of Year Bonus": "Бонус в конце года",
  Default: "Категория не определена",
};
